### PR TITLE
Updated Tests: Unit, Validity & Performance Tests

### PR DESCRIPTION
**Pull request by aklie8**
## Description
This pull request enhances the test suite for the Rust CLI project based on recent updates in core functionality. The tests cover key functionalities such as generating cipher suites, signing and verifying files, managing cipher suites in wallets, and handling various edge cases and performance scenarios.

## Changes Made
- Using the CipherSuite struct directly to represent the cipher suite configuration, iInstead of using the Persona struct to represent an individual and their associated cipher suite, 
- Tests the operations by directly interacting with the cipher suite instances, without the abstraction of personas.
- Updated unit tests to verify the generation of new cipher suites for each supported algorithm.
- Implemented tests for signing and verifying operations using Header and SignedData structs for each cipher suite.
- Updated test case to validate the removal of cipher suites from the wallet.
- Added edge case tests to handle scenarios like invalid cipher suite IDs, signing empty files, signing large files, and dealing with invalid file paths.
- Implemented performance tests to measure key generation, signing, and verification times for each cipher suite.
- Provided documentation and comments for clarity and understanding.

### Unit Tests
1. **test_generate_new_cipher_suite**: Verifies the generation of new cipher suites for each supported algorithm.
2. **test_sign_and_verify_with_header**: Tests sign and verify operations using Header and SignedData structs.
3. **test_remove_ciphersuite**: Validates the removal of cipher suites from the wallet.

### Edge Case Tests
1. **test_invalid_cipher_suite_id**: Ensures handling of invalid cipher suite IDs by create_ciphersuite function.
2. **test_sign_empty_file**: Tests signing of empty files using each cipher suite.
3. **test_sign_large_file**: Tests signing of large files (10 MB) using each cipher suite.
4. **test_invalid_file_paths**: Validates handling of invalid file paths during sign and verify operations.

### Performance Tests
1. **measure_cipher_suite_performance & test_performance**: Measures and prints the performance of key generation, signing, and verification time for each cipher suite.

### CODE REVIEW

**Comment by imeltsner** [comment]
Great work on these tests! I just have a few small comments about the performance tests. For signing, it looks like you start the timer and then create some temp files. Consider creating the temp files before starting the timer, since file creation is not technically part of the signing process. Also, for sign and verify, it looks like you clone the ciphersuite. This is also an operation that could affect the timing, so if possible, consider moving the clone to before the timer is started, so only the sign and verify operation are being timed. Lastly, since some of the tests show 0ms, we could use a smaller interval of time if it shows a more interesting result.

**Comment by aklie8** [comment]
Thanks for sharing, I'll take a look at that.

**Comment by aklie8** [comment]
As suggested, In this updated version:
1. The file creation for signing is moved before the start_sign timer, ensuring that file creation is not included in the signing time measurement.
2. The cipher suite clone operation (let cs_clone = test_cs.clone();) is moved outside the timed blocks for signing and verification, ensuring that the cloning time is not included in the measurements.
3. Instead of measuring the elapsed time in milliseconds, we now measure it in nanoseconds (as_nanos()), which provides better precision for shorter operations.

**Comment by imeltsner** [comment]
> As suggested, In this updated version of the performance test:
> 
> 1. The file creation for signing is moved before the start_sign timer, ensuring that file creation is not included in the signing time measurement.
> 2. The cipher suite clone operation (let cs_clone = test_cs.clone();) is moved outside the timed blocks for signing and verification, ensuring that the cloning time is not included in the measurements.
> 3. Instead of measuring the elapsed time in milliseconds, we now measure it in nanoseconds (as_nanos()), which provides better precision for shorter operations.
> 
> please review and let me know if we're good to merge

Looks great! Approved.

**Comment by aklie8** [comment]
Merged.

**Pull request merged**
